Repository KhronosGroup/Vulkan-Tools, pull requests merged in 2020-04, with the labels that each got.

#367 build: Update MoltenVK version in known-good.json
  scripts/known_good.json
Labels: known-good

#369 icd: Fix vkAcquireNextImageKHR generation
  icd/generated/mock_icd.cpp
  scripts/mock_icd_generator.py
Labels: MockICD, enhancement

#368 icd: Fix vkGetSwapchainImages behavior
  icd/generated/mock_icd.cpp
  scripts/mock_icd_generator.py
Labels: MockICD, enhancement

#371 mockicd:Track memory allocation size
  icd/generated/mock_icd.cpp
  scripts/mock_icd_generator.py
Labels: MockICD, enhancement

#374 build: Remove glslang dependancy from known-good
  scripts/known_good.json
Labels: enhancement, known-good

#375 icd: Make VkPhysicalDevice unique
  icd/generated/mock_icd.cpp
  scripts/mock_icd_generator.py
Labels: MockICD, enhancement

#390 vulkaninfo: Meet extension version dependencies
  vulkaninfo/vulkaninfo.h
Labels: vulkaninfo
